### PR TITLE
Cache miss async rendering

### LINKED ISSUE #87: Async Cache Misses Render Empty or Out of Order
I am setting my own async cache strategy. When the cache is empty and I `resolve(null)` in `get`, the rendered output of the component is being inserted later on in the output in the wrong place. It seems as if the component with a cacheKey is being rendered as the last child even if it is not the last child. I think renderChildren must be emitting all of the non-cached childen before the cached ones, probably because they're not waiting for `.then` to emit.

### PR DESCRIPTION
**Pull request by ethersage**
When using an async cache strategy and there's a cache miss, segments were being rendered out of order or not at all. This is caused by the fact that the cache segment is returning a promise, but the sequence continued to allow the emission of segments before the cache had resolved.

This PR makes almost everything a promise and builds a chain of promises where the next item in the sequence must wait for the previous item to render.

@divmain @maxgalbu

Resolves #87 

TODO:
- [x] tests
- [x] benchmarks

```
rapscallion{cache-miss}$ npm run benchmark

> rapscallion@2.1.7 benchmark /Users/jkaminetsky/dev/oss/rapscallion
> babel-node benchmark/benchmark.js

Starting benchmark for 10 concurrent render operations...
renderToString took 11.445220171 seconds
rapscallion, no caching took 43.507448408 seconds; ~0.26x faster
rapscallion, caching DIVs took 8.118688945 seconds; ~1.4x faster
rapscallion, caching DIVs (second time) took 8.136480110 seconds; ~1.4x faster
rapscallion, caching Components took 0.644866469 seconds; ~17.74x faster
rapscallion, caching Components (second time) took 13.052715387 seconds; ~0.87x faster
rapscallion (pre-rendered), no caching took 24.778552483 seconds; ~0.46x faster
rapscallion (pre-rendered), caching DIVs took 8.361157752 seconds; ~1.36x faster
rapscallion (pre-rendered), caching DIVs (second time) took 7.835752739 seconds; ~1.46x faster
rapscallion (pre-rendered), caching Components took 13.324269605 seconds; ~0.85x faster
rapscallion (pre-rendered), caching Components (second time) took 13.924382979 seconds; ~0.82x faster
```

### CODE REVIEW

File: src/consumers/common.js [hunk 1]
```diff
@@ -2,9 +2,21 @@ const Promise = require("bluebird");
...
+    return EXHAUSTED;
+  } else if (nextVal instanceof Promise) {
+    return nextVal
+    .then(push)
+    .then(() => iter < max && next(renderer, iter + 1, push));
+  } else {
+    push(nextVal);
+    return Promise.resolve(nextVal);
+  }
+}
```
Comment (ethersage) [inline src/consumers/common.js]: recursively build a chain of promises resolving to values to render so we can wait on an async cache get.

File: src/sequence/sequence.js [hunk 2]
```diff
@@ -30,7 +31,7 @@ class Sequence {
     this.cursor = 0;
 
     // Let the delegate do its thing...
-    delegate();
+    return delegate();
```
Comment (ethersage) [inline src/sequence/sequence.js]: This can be a promise.

File: src/consumers/common.js (hunk 1 above)
Comment (ethersage) [inline src/consumers/common.js]: Could probably find a more elegant way to do this iteration. The crux of the issue is that the previous promise has to resolve before we can invoke kick off the next promise. Any other solution requires a new library or babel preset and I wasn't sure if that would be desirable. If anyone knows how to do this with `bluebird` please let me know!

Some other options:
- https://caolan.github.io/async/docs.html#series
- https://github.com/dbushong/async-q#series
- ES6 generators

Comment (ethersage) [inline src/consumers/common.js]: http://bluebirdjs.com/docs/api/promise.coroutine.html looks promising

**Comment by ethersage** [comment]
@jvivs Check this out.

@divmain

**Comment by maxgalbu** [comment]
Something's not right in that benchmark, how can the second pass with cached components take longer than the first pass of caching?

**Comment by divmain** [comment]
I'm going to want to take a look at this more closely.  Those benchmarks indicate a significant performance regression.  There might be a better-performing solution to the issues raised here.

**Comment by ethersage** [comment]
My first guess would be overhead from naive promise implementation, specifically waiting for all segments to resolve in series, even when there's not an async cache get.

File: spec/cache.js [hunk 3]
```diff
@@ -45,6 +57,18 @@ const runAllTests = () => {
...
+      return Bluebird.resolve()
+        .then(() => render(<Parent val="firstB" parentKey={parentKey} />)
+          .includeDataReactAttrs(false)
+          .toPromise()
+        )
+        .then(html => {
+          expect(html).to.equal("<div>firstB</div>");
+        });
+    });
+
```
Comment (divmain) [inline spec/cache.js]: Do these tests fail in current master?

**Comment by clifton** [comment]
I'm not sure how much you should index to the benchmark when async caching doesn't seem to be working properly in the first place. ex: https://github.com/Rymar/rapscalion-cache is the exact problem I'm finding when trying to do async caching in a production application

File: spec/cache.js (hunk 3 above)
Comment (ethersage) [inline spec/cache.js]: @divmain Yes

**Comment by ethersage** [comment]
Honestly the benchmarks on master don't look much different:

```Starting benchmark for 10 concurrent render operations...
renderToString took 11.486885729 seconds
rapscallion, no caching took 43.693205031 seconds; ~0.26x faster
rapscallion, caching DIVs took 16.163418342 seconds; ~0.71x faster
rapscallion, caching DIVs (second time) took 14.280983280 seconds; ~0.8x faster
rapscallion, caching Components took 0.701809205 seconds; ~16.36x faster
rapscallion, caching Components (second time) took 15.668481997 seconds; ~0.73x faster
rapscallion (pre-rendered), no caching took 35.028802432 seconds; ~0.32x faster
rapscallion (pre-rendered), caching DIVs took 18.111153076 seconds; ~0.63x faster
rapscallion (pre-rendered), caching DIVs (second time) took 17.383266673 seconds; ~0.66x faster
rapscallion (pre-rendered), caching Components took 16.657128768 seconds; ~0.68x faster
rapscallion (pre-rendered), caching Components (second time) took 16.814332255 seconds; ~0.68x faster```

**Comment by ethersage** [comment]
Now back on this `cache-miss` branch, executed immediately afterwards with similar load on same machine:

```
renderToString took 11.203203946 seconds
rapscallion, no caching took 41.365911048 seconds; ~0.27x faster
rapscallion, caching DIVs took 15.757512965 seconds; ~0.71x faster
rapscallion, caching DIVs (second time) took 13.955430961 seconds; ~0.8x faster
rapscallion, caching Components took 0.529333810 seconds; ~21.16x faster
rapscallion, caching Components (second time) took 12.946540060 seconds; ~0.86x faster
rapscallion (pre-rendered), no caching took 25.377965259 seconds; ~0.44x faster
rapscallion (pre-rendered), caching DIVs took 13.801301708 seconds; ~0.81x faster
rapscallion (pre-rendered), caching DIVs (second time) took 13.337650601 seconds; ~0.83x faster
rapscallion (pre-rendered), caching Components took 13.305775981 seconds; ~0.84x faster
rapscallion (pre-rendered), caching Components (second time) took 12.985989510 seconds; ~0.86x faster
```

It might actually be faster, granted the smallest of sample sizes in a personal computing environment.

**Comment by divmain** [comment]
I pulled this down and you're right - the benchmarks don't look much difference between v2.1.7 and your branch, although it seems to perform much better against React on my machine.

@ethersage, can you clean up the merge conflicts?  I'll follow up with publishing a new version.

**Comment by ethersage** [comment]
I will look at merge conflicts

**Comment by ethersage** [comment]
@fleg Please review where I've tagged you to make sure I merged correctly.

File: src/consumers/common.js [hunk 4]
```diff
@@ -2,9 +2,27 @@ const Promise = require("bluebird");
...
 
+function next (renderer, iter, push) {
+  const max = renderer.batchSize;
+  let nextVal;
+
+  try {
+    nextVal = renderer._next();
+  } catch (err) {
+    return Promise.reject(err);
+  }
```
Comment (ethersage) [inline src/consumers/common.js]: @fleg Please confirm I merged correctly.

File: src/consumers/node-stream.js [hunk 5]
```diff
@@ -19,20 +18,20 @@ function toNodeStream (renderer) {
...
+        stream.push(result);
         read();
-      }).catch(err => {
-        stream.emit("error", err);
-      });
-    }
+      }
+    }).catch(err => {
+      stream.emit("error", err);
+    });
```
Comment (ethersage) [inline src/consumers/node-stream.js]: @fleg Please confirm I merged correctly.

File: src/consumers/promise.js [hunk 6]
```diff
@@ -19,19 +16,23 @@ function asyncBatch (
...
+        asyncBatch,
+        renderer,
+        pushable,
+        resolve,
+        reject,
+      );
+    }
+  }).catch(err => {
+    reject(err);
+  });
```
Comment (ethersage) [inline src/consumers/promise.js]: @fleg Please confirm I merged correctly.

**Comment by fleg** [comment]
lgtm, what about tests?

**Comment by ethersage** [comment]
Tests look good to me.

**Comment by divmain** [comment]
Alrighty, I think this is ready to ship.  Thanks for your work on this!
